language: java

env:
  - ANDROID_HOME=$PWD/android-sdk

# Skip the install step, gradlew assemble will fail due to Crashlytics
install: true

jdk:
  - oraclejdk8

before_install:
  - rvm install 2.3.4
  - gem install android-sdk-installer
  - android-sdk-installer -i

script: "./gradlew testDebug"
